/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    scholarships: Scholarship;
    applications: Application;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    scholarships: ScholarshipsSelect<false> | ScholarshipsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    home: Home;
    about: About;
    contact: Contact;
    faq: Faq;
    'scholarship-page': ScholarshipPage;
    apply: Apply;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'scholarship-page': ScholarshipPageSelect<false> | ScholarshipPageSelect<true>;
    apply: ApplySelect<false> | ApplySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarships".
 */
export interface Scholarship {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  description: string;
  isActive?: boolean | null;
  eligibility: {
    value: string;
    id?: string | null;
  }[];
  benefits: {
    itemId: string;
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  teachers: {
    subject: string;
    name: string;
    id?: string | null;
  }[];
  requiredDocuments: {
    itemId: string;
    title: string;
    description?: string | null;
    required?: boolean | null;
    id?: string | null;
  }[];
  selectionProcess: {
    value: string;
    id?: string | null;
  }[];
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  guardianPhone: string;
  target: 'jee' | 'neet';
  board: 'wbbse' | 'cbse' | 'icse' | 'other';
  schoolName: string;
  class8Percentage: number;
  class9Percentage: number;
  class10PreBoardPercentage: number;
  class10TotalMarks: number;
  class10MaxMarks: number;
  subject1Name: string;
  subject1Obtained: number;
  subject1Max: number;
  subject2Name: string;
  subject2Obtained: number;
  subject2Max: number;
  subject3Name: string;
  subject3Obtained: number;
  subject3Max: number;
  subject4Name: string;
  subject4Obtained: number;
  subject4Max: number;
  subject5Name: string;
  subject5Obtained: number;
  subject5Max: number;
  /**
   * Auto-calculated from Class 8 → 9 → 10 percentages.
   */
  academicTrend: 'improving' | 'stable' | 'declining';
  /**
   * Auto-calculated average percentage-point change (Class 8→9 and 9→10).
   */
  trendScore: number;
  academicAchievements?: string | null;
  address: string;
  parentsName: string;
  parentsProfession: string;
  /**
   * Whole number amount in INR
   */
  householdIncome: number;
  status: 'new' | 'reviewed' | 'shortlisted' | 'rejected';
  /**
   * Set automatically when the Google Form invite email is sent.
   */
  formInviteSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'scholarships';
        value: number | Scholarship;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        logo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarships_select".
 */
export interface ScholarshipsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  isActive?: T;
  eligibility?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        itemId?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  teachers?:
    | T
    | {
        subject?: T;
        name?: T;
        id?: T;
      };
  requiredDocuments?:
    | T
    | {
        itemId?: T;
        title?: T;
        description?: T;
        required?: T;
        id?: T;
      };
  selectionProcess?:
    | T
    | {
        value?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  guardianPhone?: T;
  target?: T;
  board?: T;
  schoolName?: T;
  class8Percentage?: T;
  class9Percentage?: T;
  class10PreBoardPercentage?: T;
  class10TotalMarks?: T;
  class10MaxMarks?: T;
  subject1Name?: T;
  subject1Obtained?: T;
  subject1Max?: T;
  subject2Name?: T;
  subject2Obtained?: T;
  subject2Max?: T;
  subject3Name?: T;
  subject3Obtained?: T;
  subject3Max?: T;
  subject4Name?: T;
  subject4Obtained?: T;
  subject4Max?: T;
  subject5Name?: T;
  subject5Obtained?: T;
  subject5Max?: T;
  academicTrend?: T;
  trendScore?: T;
  academicAchievements?: T;
  address?: T;
  parentsName?: T;
  parentsProfession?: T;
  householdIncome?: T;
  status?: T;
  formInviteSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  shortName: string;
  description: string;
  tagline: string;
  email: string;
  phone: string;
  address: string;
  /**
   * Google Form link emailed to selected shortlisted applicants for follow-up details and documents. Public Apply CTAs still use the in-app /apply form.
   */
  applyUrl?: string | null;
  /**
   * Subject line for the Google Form invite email.
   */
  shortlistEmailSubject?: string | null;
  /**
   * Email body sent to selected shortlisted applicants. Use {{fullName}} and {{formUrl}} as placeholders.
   */
  shortlistEmailBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  locale: string;
  author: string;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  navigation: {
    title: string;
    href: string;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    badge: string;
    title: string;
    highlightedTitle: string;
    description: string;
    primaryCta: string;
    secondaryCta: string;
    stats: {
      value: string;
      label: string;
      id?: string | null;
    }[];
  };
  sections: {
    scholarships: {
      title: string;
      description?: string | null;
    };
    benefits: {
      title: string;
      description?: string | null;
    };
    applicationProcess: {
      title: string;
      description?: string | null;
    };
    faqs: {
      title: string;
      description?: string | null;
    };
  };
  benefits: {
    title: string;
    description: string;
    icon:
      'Award' | 'BookOpen' | 'Brain' | 'FileText' | 'GraduationCap' | 'Mail' | 'MapPin' | 'Phone' | 'Trophy' | 'Users';
    id?: string | null;
  }[];
  applicationSteps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  heading: {
    title: string;
    description?: string | null;
  };
  sections: {
    title: string;
    body?: string | null;
    items?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  heading: {
    title: string;
    description?: string | null;
  };
  infoItems: {
    itemId: string;
    title: string;
    icon:
      'Award' | 'BookOpen' | 'Brain' | 'FileText' | 'GraduationCap' | 'Mail' | 'MapPin' | 'Phone' | 'Trophy' | 'Users';
    type: 'email' | 'phone' | 'address';
    lines?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  enquiry: {
    title: string;
    body: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  heading: {
    title: string;
    description?: string | null;
  };
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  homePreviewQuestions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship-page".
 */
export interface ScholarshipPage {
  id: number;
  list: {
    title: string;
    description: string;
    metaDescription: string;
  };
  detail: {
    sectionTitles: {
      benefits: string;
      eligibility: string;
      faculty: string;
      documents: string;
      selectionProcess: string;
    };
    sidebar: {
      title: string;
      description: string;
      features: {
        label: string;
        icon:
          | 'Award'
          | 'BookOpen'
          | 'Brain'
          | 'FileText'
          | 'GraduationCap'
          | 'Mail'
          | 'MapPin'
          | 'Phone'
          | 'Trophy'
          | 'Users';
        id?: string | null;
      }[];
      footerNote: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply".
 */
export interface Apply {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  heading: {
    title: string;
    description?: string | null;
  };
  form: {
    labels: {
      fullName: string;
      email: string;
      phone: string;
      guardianPhone: string;
      target: string;
      board: string;
      schoolName: string;
      class8Percentage: string;
      class9Percentage: string;
      class10PreBoardPercentage: string;
      class10TotalMarks: string;
      class10MaxMarks: string;
      subjectName: string;
      subjectObtained: string;
      subjectMax: string;
      academicAchievements: string;
      address: string;
      parentsName: string;
      parentsProfession: string;
      householdIncome: string;
      selectPlaceholder: string;
    };
    options: {
      targetJee: string;
      targetNeet: string;
      boardWbbse: string;
      boardCbse: string;
      boardIcse: string;
      boardOther: string;
    };
    sections: {
      personalTitle: string;
      familyTitle: string;
      percentagesTitle: string;
      percentagesHelp: string;
      totalsTitle: string;
      subjectsTitle: string;
      subjectsHelp: string;
    };
    subjectDefaults: {
      value: string;
      id?: string | null;
    }[];
    success: {
      title: string;
      body: string;
      resetLabel: string;
    };
    errors: {
      submissionFailed: string;
      network: string;
      server: string;
    };
    submit: {
      idle: string;
      pending: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  description?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  applyUrl?: T;
  shortlistEmailSubject?: T;
  shortlistEmailBody?: T;
  logo?: T;
  favicon?: T;
  locale?: T;
  author?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        title?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        highlightedTitle?: T;
        description?: T;
        primaryCta?: T;
        secondaryCta?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        scholarships?:
          | T
          | {
              title?: T;
              description?: T;
            };
        benefits?:
          | T
          | {
              title?: T;
              description?: T;
            };
        applicationProcess?:
          | T
          | {
              title?: T;
              description?: T;
            };
        faqs?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  applicationSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heading?:
    | T
    | {
        title?: T;
        description?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        items?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heading?:
    | T
    | {
        title?: T;
        description?: T;
      };
  infoItems?:
    | T
    | {
        itemId?: T;
        title?: T;
        icon?: T;
        type?: T;
        lines?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  enquiry?:
    | T
    | {
        title?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heading?:
    | T
    | {
        title?: T;
        description?: T;
      };
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  homePreviewQuestions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship-page_select".
 */
export interface ScholarshipPageSelect<T extends boolean = true> {
  list?:
    | T
    | {
        title?: T;
        description?: T;
        metaDescription?: T;
      };
  detail?:
    | T
    | {
        sectionTitles?:
          | T
          | {
              benefits?: T;
              eligibility?: T;
              faculty?: T;
              documents?: T;
              selectionProcess?: T;
            };
        sidebar?:
          | T
          | {
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              footerNote?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply_select".
 */
export interface ApplySelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heading?:
    | T
    | {
        title?: T;
        description?: T;
      };
  form?:
    | T
    | {
        labels?:
          | T
          | {
              fullName?: T;
              email?: T;
              phone?: T;
              guardianPhone?: T;
              target?: T;
              board?: T;
              schoolName?: T;
              class8Percentage?: T;
              class9Percentage?: T;
              class10PreBoardPercentage?: T;
              class10TotalMarks?: T;
              class10MaxMarks?: T;
              subjectName?: T;
              subjectObtained?: T;
              subjectMax?: T;
              academicAchievements?: T;
              address?: T;
              parentsName?: T;
              parentsProfession?: T;
              householdIncome?: T;
              selectPlaceholder?: T;
            };
        options?:
          | T
          | {
              targetJee?: T;
              targetNeet?: T;
              boardWbbse?: T;
              boardCbse?: T;
              boardIcse?: T;
              boardOther?: T;
            };
        sections?:
          | T
          | {
              personalTitle?: T;
              familyTitle?: T;
              percentagesTitle?: T;
              percentagesHelp?: T;
              totalsTitle?: T;
              subjectsTitle?: T;
              subjectsHelp?: T;
            };
        subjectDefaults?:
          | T
          | {
              value?: T;
              id?: T;
            };
        success?:
          | T
          | {
              title?: T;
              body?: T;
              resetLabel?: T;
            };
        errors?:
          | T
          | {
              submissionFailed?: T;
              network?: T;
              server?: T;
            };
        submit?:
          | T
          | {
              idle?: T;
              pending?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}